### ISSUE TITLE
Should all files be executable? Should we implement modes?

### ISSUE THREAD

**Issue by sgielen** [Jille/rufs#46]

**Comment by Jille** [comment]
People probably shouldn't run executables from RUFS?

Is this a user feature request?

**Comment by Jille** [comment]
We seem to always use 644 for non-directories (in both fuse implementations):

```
  if file.IsDirectory {
    attr.Mode = 0755 | fuse.S_IFDIR
  } else {
    attr.Mode = 0644 | fuse.S_IFREG
  }
```

@marrit-git can you give me the output of `ls -l` or `stat(1)`?

**Comment by marrit-git** [comment]
You're right, 644 is used. My distro warns that the file is executable when opening the file through the GUI, but no +x flag is set. Seems to be a local quirk.

```
File: 'rufs-warnings.txt'
Size: 1353      	Blocks: 0          IO Block: 4096   regular file
Device: 31h/49d	Inode: 208815898845939238  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-06-19 22:18:38.423387049 +0200
Modify: 2021-06-19 22:22:06.839887985 +0200
Change: 2021-06-19 22:18:38.423387049 +0200
 Birth: -
```
